server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/domoticasd?serverTimezone=UTC
    username: root
    password:
    driverclassname: com.mysql.cj.jdbc.Driver
